// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pobiuxmbihytsqgoygjw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBvYml1eG1iaWh5dHNxZ295Z2p3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY0MDAyMzksImV4cCI6MjA3MTk3NjIzOX0.AuHF7M883vr1dmwWJps2UNrT6rukbPxiuMcnpR_A5jo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});